// Per-agent edit/save workflow for Team Vince Daily Input
const baseRender = render;
const dailyDrafts = JSON.parse(localStorage.getItem('vinceDailyDrafts') || '{}');
let editingAgent = null;
function money(v){return '$'+(+v||0).toLocaleString(undefined,{maximumFractionDigits:2})}
function dailyV2(){return `<div class=notice>The historical workbook baseline is preserved. Click <b>Edit</b> on the agent you want to update; only that row becomes editable. Click <b>Save</b> when finished.</div><div class=card><h3>Current Baseline + Daily Entry</h3><div style="overflow-x:auto"><table><tr><th>Agent</th><th>Outbound</th><th>Inbound</th><th>Invoices</th><th>Quotes</th><th>Accounts</th><th>Revenue</th><th>Today's Note</th><th style="text-align:right">Action</th></tr>${data.map((a,i)=>{let e=editingAgent===i,d=dailyDrafts[a.id]||{};const val=(k)=>d[k]??a[k]??0;return `<tr class="${e?'editing-row':''}"><td><b>${a.name}</b><br><small>${a.wave}</small></td>${['outbound','inbound','invoices','quotes','accounts'].map(k=>`<td>${e?`<input class=row-input type=number min=0 value="${val(k)}" data-i="${i}" data-k="${k}">`:(a[k]||'—')}</td>`).join('')}<td>${e?`<input class="row-input revenue-input" type=number min=0 step=.01 value="${val('revenue')}" data-i="${i}" data-k="revenue">`:money(a.revenue)}</td><td>${e?`<input class=note-input value="${(d.note||'').replace(/"/g,'&quot;')}" placeholder="Enter today's update" data-i="${i}" data-k="note">`:`<span class=note-view>${d.note||'—'}</span>`}</td><td class=action-cell>${e?`<button class="save-row" onclick="saveAgentRow(${i})">✓ Save</button><button class="cancel-row" onclick="cancelAgentRow()">Cancel</button>`:`<button class="edit-row" onclick="editAgentRow(${i})">✎ Edit</button>`}</td></tr>`}).join('')}</table></div></div>`}
function editAgentRow(i){editingAgent=i;render()}
function cancelAgentRow(){editingAgent=null;render()}
function saveAgentRow(i){const a=data[i],draft=dailyDrafts[a.id]||{};document.querySelectorAll(`[data-i="${i}"]`).forEach(el=>{draft[el.dataset.k]=el.dataset.k==='note'?el.value:+el.value});dailyDrafts[a.id]=draft;['outbound','inbound','invoices','quotes','accounts','revenue'].forEach(k=>{if(draft[k]!==undefined)a[k]=draft[k]});localStorage.setItem('vinceDailyDrafts',JSON.stringify(dailyDrafts));editingAgent=null;render()}
render=function(){baseRender();if(tab==='Daily Input')app.innerHTML=dailyV2()};
